FORMAT: 1A
HOST: http://api.pinnaclesports.com/admin/responsible-gaming

# Admin

As a logged in partner, you can perform any action on our backend services.

## Headers

`Content-Type: application/json`

`Authorization: {partner-token}`

## Response Codes

<table> 
    <tr> 
        <td>200</td><td nowrap><code>OK</code></td> 
    </tr> 
    <tr> 
        <td>201</td><td nowrap><code>Created</code></td> 
    </tr> 
    <tr> 
        <td>204</td><td nowrap><code>No Content</code></td> 
    </tr>
    <tr> 
        <td>400</td><td nowrap><code>Bad Request</code></td> 
    </tr> 
    <tr> 
        <td>401</td><td nowrap><code>Unauthorized</code></td> 
    </tr>
        <tr> 
        <td>404</td><td nowrap><code>Not found</code></td> 
    </tr>
    <tr> 
        <td>500</td><td nowrap><code>Internal Server Error</code></td> 
    </tr> 
</table> 

#Group Responsible gaming

## Customers with limits [/customers-with-limits]

### Retrieve [GET]


+ Request (application/json)

    + Headers
         
            Authorization: {token}  

+ Response 200

    + Body
    
            [
                {
                  "customerId": "test1"
                },
                {
                  "customerId": "test2"
                }
            ]

+ Response 401

+ Response 404

+ Response 500


## Deposit limit [/deposit-limit/{customerId}]

### Retrieve [GET]

+ Parameters
    + customerId (string, optional)

+ Request (application/json)

    + Headers
         
            Authorization: {token}  

+ Response 200

    + Body
    
            {
                "PeriodInHours": 672,
                "PeriodInDays": 28,
                "StartDate": "2016-05-19T09:29",
                "CurrentCycleStartDate": "2016-05-19T09:29",
                "Amount": 100,
                "Status": "Active",
                "AddedBy": "cesarc",
                "DateAdded":"2016-05-19T09:29"
            }

+ Response 401

+ Response 404

+ Response 500

### Set [PUT]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Authorization: {token}  
    + Body
        
            {
                "PeriodInHours": 672,
                "StartDate": "2016-05-19T09:29",
                "Amount": 100,
                "AddedBy": "cesarc"
            }

+ Response 204

+ Response 400 (application/json)

    + Body
            
            {
                "message": "The request is invalid.",
                "errors": 
                    {
                        "request.PeriodInHours": ["A positive number is expected"],
                        "request.StartDate": ["The field is mandatory"],
                        "request.Amount": ["A positive number is expected"],
                        "request.AddedBy": ["The field is mandatory"]
                    }
            }
            
+ Response 401

+ Response 500

### Disable [DELETE]

+ Request

    + Headers
         
            Authorization: {token}  


+ Response 204

+ Response 500

## Self-exclusion [/self-exclusion/{customerId}]

### Retrieve [GET]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Accept-Language: en-GB
            Authorization: {token}  

+ Response 200

    + Body
    
            {
                "PeriodInHours": 672,
                "PeriodInDays": 28,
                "StartDate": "2016-05-19T09:29",
                "EndDate": "2016-06-16T09:29",
                "Status": "Active",
                "AddedBy": "cesarc",
                "DateAdded":"2016-05-19T09:29"
            }

+ Response 401

+ Response 404 

+ Response 500

### Set [PUT]

+ Request(application/json)

    + Headers
         
            Authorization: {token}  
    + Body
        
            {
                "period": 672
            }

+ Response 204

+ Response 400 (application/json)

    + Body
            
            {
                "message": "The request is invalid.",
                "errors": 
                    {
                        "request.period": ["The provided period is not allowed"]
                    }
            }
            
+ Response 401

+ Response 500

### Disable [DELETE]

+ Request

    + Headers
         
            Authorization: {token}  


+ Response 204

+ Response 500

## Cooling-off period [/cooling-off-period/{customerId}]

### Retrieve [GET]

+ Parameters

    + customerId (string)

+ Request

    + Headers
         
            Content-Type: application/json
            Authorization: {token}  

+ Response 200

    + Body
    
            {
              "coolingOffPeriodInHours": 24
            }

+ Response 401

+ Response 404

+ Response 500